### PR TITLE
matcher: create Matcher struct with integration tests

### PR DESCRIPTION
**Pull request by ihrwein**
The Matcher struct is a high level structure to create a parser  instance.
It's purpose its to abstract away the details of parser creation and to
provide a simple interface to the users. Currenty it has two methods:

* from_file() creates a parser, where the patterns are listed in a file
* parse() can be used to parse texts into key-value pairs

Signed-off-by: Tibor Benke <tibor.benke@balabit.com>

### CODE REVIEW

**Comment by ihrwein** [comment]
@lbudai: Would you review this? I'll refactor the `adbtool` binary based on this commit).

**Comment by ihrwein** [comment]
@lbudai: I've finished the refactor, the PR is ready to review.

**Comment by dnsjts** [comment]
:+1:

**Comment by ihrwein** [comment]
Thanks!

**Pull request merged**
